#ifdef _VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED

#undef VEILER_PELOPS_LUPEGEM_USING_HEADER
#undef VEILER_PELOPS_LUPEGEM_USING
#undef VEILER_PELOPS_LUPEGEM_USING_0
#undef VEILER_PELOPS_LUPEGEM_USING_1
#undef VEILER_PELOPS_LUPEGEM_USING_0_END
#undef VEILER_PELOPS_LUPEGEM_USING_1_END
#undef VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED

#endif //_VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED

//Copyright (C) 2012 I
//  Distributed under the Veiler Source License 1.0.
