//Copyright (C) 2012-2017 I
//  Distributed under the Boost Software License, Version 1.0.
//  (See accompanying file LICENSE.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#ifdef _VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED

#undef VEILER_PELOPS_LUPEGEM_USING_HEADER
#undef VEILER_PELOPS_LUPEGEM_USING
#undef VEILER_PELOPS_LUPEGEM_USING_0
#undef VEILER_PELOPS_LUPEGEM_USING_1
#undef VEILER_PELOPS_LUPEGEM_USING_0_END
#undef VEILER_PELOPS_LUPEGEM_USING_1_END
#undef VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED

#endif //_VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED
