#ifdef _VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED

#undef VEILER_PELOPS_LUPEGEM_USING_HEADER
#undef VEILER_PELOPS_LUPEGEM_USING
#undef _VEILER_PELOPS_LUPEGEM_USING_
#undef _VEILER_PELOPS_LUPEGEM_USING__
#undef _VEILER_PELOPS_LUPEGEM_USING__END
#undef _VEILER_PELOPS_LUPEGEM_USING___END
#undef _VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED

#endif //_VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED

//Copyright (C) 2012 I
//  Distributed under the Veiler Source License 1.0.
