#ifndef VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED
#define VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED

#include"../lupe.hpp"

#ifndef VEILER_PELOPS_LUPEGEM_USING_HEADER
#define VEILER_PELOPS_LUPEGEM_USING_HEADER
#endif

#define VEILER_PELOPS_LUPEGEM_USING(args) VEILER_PELOPS_LUPE(VEILER_PELOPS_LUPEGEM_USING_0,args)

#define VEILER_PELOPS_LUPEGEM_USING_0(arg) using VEILER_PELOPS_ULLR_CAT(VEILER_PELOPS_LUPEGEM_USING_HEADER,arg); VEILER_PELOPS_LUPEGEM_USING_1
#define VEILER_PELOPS_LUPEGEM_USING_1(arg) using VEILER_PELOPS_ULLR_CAT(VEILER_PELOPS_LUPEGEM_USING_HEADER,arg); VEILER_PELOPS_LUPEGEM_USING_0

#define VEILER_PELOPS_LUPEGEM_USING_0_END
#define VEILER_PELOPS_LUPEGEM_USING_1_END

#endif //VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED

//Copyright (C) 2012 I
//  Distributed under the Veiler Source License 1.0.
