//Copyright (C) 2012-2017 I
//  Distributed under the Boost Software License, Version 1.0.
//  (See accompanying file LICENSE.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#ifndef VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED
#define VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED

#include"../lupe.hpp"

#ifndef VEILER_PELOPS_LUPEGEM_USING_HEADER
#define VEILER_PELOPS_LUPEGEM_USING_HEADER
#endif

#define VEILER_PELOPS_LUPEGEM_USING(args) VEILER_PELOPS_LUPE(VEILER_PELOPS_LUPEGEM_USING_0_,args)

#define VEILER_PELOPS_LUPEGEM_USING_0_(arg) using VEILER_PELOPS_ULLR_CAT(VEILER_PELOPS_LUPEGEM_USING_HEADER,arg); VEILER_PELOPS_LUPEGEM_USING_1_
#define VEILER_PELOPS_LUPEGEM_USING_1_(arg) using VEILER_PELOPS_ULLR_CAT(VEILER_PELOPS_LUPEGEM_USING_HEADER,arg); VEILER_PELOPS_LUPEGEM_USING_0_

#define VEILER_PELOPS_LUPEGEM_USING_0_END
#define VEILER_PELOPS_LUPEGEM_USING_1_END

#endif //VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED
