#ifndef _VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED
#define _VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED

#include"../lupe.hpp"

#ifndef VEILER_PELOPS_LUPEGEM_USING_HEADER
#define VEILER_PELOPS_LUPEGEM_USING_HEADER
#endif

#define VEILER_PELOPS_LUPEGEM_USING(args) VEILER_PELOPS_LUPE(_VEILER_PELOPS_LUPEGEM_USING_,args)

#define _VEILER_PELOPS_LUPEGEM_USING_(arg) using VEILER_PELOPS_ULLR_CAT(VEILER_PELOPS_LUPEGEM_USING_HEADER,arg); _VEILER_PELOPS_LUPEGEM_USING__
#define _VEILER_PELOPS_LUPEGEM_USING__(arg) using VEILER_PELOPS_ULLR_CAT(VEILER_PELOPS_LUPEGEM_USING_HEADER,arg); _VEILER_PELOPS_LUPEGEM_USING_

#define _VEILER_PELOPS_LUPEGEM_USING__END
#define _VEILER_PELOPS_LUPEGEM_USING___END

#endif //_VEILER_PELOPS_LUPEGEM_USING_HPP_INCLUDED

//Copyright (C) 2012 I
//  Distributed under the Veiler Source License 1.0.
