#ifndef _VEILER_PELOPS_DIBELLA_HPP_INCLUDED
#define _VEILER_PELOPS_DIBELLA_HPP_INCLUDED

#define VEILER_PELOPS_DIBELLA(...) _VEILER_PELOPS_DIBELLA_100_()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()(__VA_ARGS__)
#define _VEILER_PELOPS_DIBELLA_0_(...) __VA_ARGS__
#define _VEILER_PELOPS_DIBELLA_1_() _VEILER_PELOPS_DIBELLA_0_
#define _VEILER_PELOPS_DIBELLA_2_() _VEILER_PELOPS_DIBELLA_1_
#define _VEILER_PELOPS_DIBELLA_3_() _VEILER_PELOPS_DIBELLA_2_
#define _VEILER_PELOPS_DIBELLA_4_() _VEILER_PELOPS_DIBELLA_3_
#define _VEILER_PELOPS_DIBELLA_5_() _VEILER_PELOPS_DIBELLA_4_
#define _VEILER_PELOPS_DIBELLA_6_() _VEILER_PELOPS_DIBELLA_5_
#define _VEILER_PELOPS_DIBELLA_7_() _VEILER_PELOPS_DIBELLA_6_
#define _VEILER_PELOPS_DIBELLA_8_() _VEILER_PELOPS_DIBELLA_7_
#define _VEILER_PELOPS_DIBELLA_9_() _VEILER_PELOPS_DIBELLA_8_
#define _VEILER_PELOPS_DIBELLA_10_() _VEILER_PELOPS_DIBELLA_9_
#define _VEILER_PELOPS_DIBELLA_11_() _VEILER_PELOPS_DIBELLA_10_
#define _VEILER_PELOPS_DIBELLA_12_() _VEILER_PELOPS_DIBELLA_11_
#define _VEILER_PELOPS_DIBELLA_13_() _VEILER_PELOPS_DIBELLA_12_
#define _VEILER_PELOPS_DIBELLA_14_() _VEILER_PELOPS_DIBELLA_13_
#define _VEILER_PELOPS_DIBELLA_15_() _VEILER_PELOPS_DIBELLA_14_
#define _VEILER_PELOPS_DIBELLA_16_() _VEILER_PELOPS_DIBELLA_15_
#define _VEILER_PELOPS_DIBELLA_17_() _VEILER_PELOPS_DIBELLA_16_
#define _VEILER_PELOPS_DIBELLA_18_() _VEILER_PELOPS_DIBELLA_17_
#define _VEILER_PELOPS_DIBELLA_19_() _VEILER_PELOPS_DIBELLA_18_
#define _VEILER_PELOPS_DIBELLA_20_() _VEILER_PELOPS_DIBELLA_19_
#define _VEILER_PELOPS_DIBELLA_21_() _VEILER_PELOPS_DIBELLA_20_
#define _VEILER_PELOPS_DIBELLA_22_() _VEILER_PELOPS_DIBELLA_21_
#define _VEILER_PELOPS_DIBELLA_23_() _VEILER_PELOPS_DIBELLA_22_
#define _VEILER_PELOPS_DIBELLA_24_() _VEILER_PELOPS_DIBELLA_23_
#define _VEILER_PELOPS_DIBELLA_25_() _VEILER_PELOPS_DIBELLA_24_
#define _VEILER_PELOPS_DIBELLA_26_() _VEILER_PELOPS_DIBELLA_25_
#define _VEILER_PELOPS_DIBELLA_27_() _VEILER_PELOPS_DIBELLA_26_
#define _VEILER_PELOPS_DIBELLA_28_() _VEILER_PELOPS_DIBELLA_27_
#define _VEILER_PELOPS_DIBELLA_29_() _VEILER_PELOPS_DIBELLA_28_
#define _VEILER_PELOPS_DIBELLA_30_() _VEILER_PELOPS_DIBELLA_29_
#define _VEILER_PELOPS_DIBELLA_31_() _VEILER_PELOPS_DIBELLA_30_
#define _VEILER_PELOPS_DIBELLA_32_() _VEILER_PELOPS_DIBELLA_31_
#define _VEILER_PELOPS_DIBELLA_33_() _VEILER_PELOPS_DIBELLA_32_
#define _VEILER_PELOPS_DIBELLA_34_() _VEILER_PELOPS_DIBELLA_33_
#define _VEILER_PELOPS_DIBELLA_35_() _VEILER_PELOPS_DIBELLA_34_
#define _VEILER_PELOPS_DIBELLA_36_() _VEILER_PELOPS_DIBELLA_35_
#define _VEILER_PELOPS_DIBELLA_37_() _VEILER_PELOPS_DIBELLA_36_
#define _VEILER_PELOPS_DIBELLA_38_() _VEILER_PELOPS_DIBELLA_37_
#define _VEILER_PELOPS_DIBELLA_39_() _VEILER_PELOPS_DIBELLA_38_
#define _VEILER_PELOPS_DIBELLA_40_() _VEILER_PELOPS_DIBELLA_39_
#define _VEILER_PELOPS_DIBELLA_41_() _VEILER_PELOPS_DIBELLA_40_
#define _VEILER_PELOPS_DIBELLA_42_() _VEILER_PELOPS_DIBELLA_41_
#define _VEILER_PELOPS_DIBELLA_43_() _VEILER_PELOPS_DIBELLA_42_
#define _VEILER_PELOPS_DIBELLA_44_() _VEILER_PELOPS_DIBELLA_43_
#define _VEILER_PELOPS_DIBELLA_45_() _VEILER_PELOPS_DIBELLA_44_
#define _VEILER_PELOPS_DIBELLA_46_() _VEILER_PELOPS_DIBELLA_45_
#define _VEILER_PELOPS_DIBELLA_47_() _VEILER_PELOPS_DIBELLA_46_
#define _VEILER_PELOPS_DIBELLA_48_() _VEILER_PELOPS_DIBELLA_47_
#define _VEILER_PELOPS_DIBELLA_49_() _VEILER_PELOPS_DIBELLA_48_
#define _VEILER_PELOPS_DIBELLA_50_() _VEILER_PELOPS_DIBELLA_49_
#define _VEILER_PELOPS_DIBELLA_51_() _VEILER_PELOPS_DIBELLA_50_
#define _VEILER_PELOPS_DIBELLA_52_() _VEILER_PELOPS_DIBELLA_51_
#define _VEILER_PELOPS_DIBELLA_53_() _VEILER_PELOPS_DIBELLA_52_
#define _VEILER_PELOPS_DIBELLA_54_() _VEILER_PELOPS_DIBELLA_53_
#define _VEILER_PELOPS_DIBELLA_55_() _VEILER_PELOPS_DIBELLA_54_
#define _VEILER_PELOPS_DIBELLA_56_() _VEILER_PELOPS_DIBELLA_55_
#define _VEILER_PELOPS_DIBELLA_57_() _VEILER_PELOPS_DIBELLA_56_
#define _VEILER_PELOPS_DIBELLA_58_() _VEILER_PELOPS_DIBELLA_57_
#define _VEILER_PELOPS_DIBELLA_59_() _VEILER_PELOPS_DIBELLA_58_
#define _VEILER_PELOPS_DIBELLA_60_() _VEILER_PELOPS_DIBELLA_59_
#define _VEILER_PELOPS_DIBELLA_61_() _VEILER_PELOPS_DIBELLA_60_
#define _VEILER_PELOPS_DIBELLA_62_() _VEILER_PELOPS_DIBELLA_61_
#define _VEILER_PELOPS_DIBELLA_63_() _VEILER_PELOPS_DIBELLA_62_
#define _VEILER_PELOPS_DIBELLA_64_() _VEILER_PELOPS_DIBELLA_63_
#define _VEILER_PELOPS_DIBELLA_65_() _VEILER_PELOPS_DIBELLA_64_
#define _VEILER_PELOPS_DIBELLA_66_() _VEILER_PELOPS_DIBELLA_65_
#define _VEILER_PELOPS_DIBELLA_67_() _VEILER_PELOPS_DIBELLA_66_
#define _VEILER_PELOPS_DIBELLA_68_() _VEILER_PELOPS_DIBELLA_67_
#define _VEILER_PELOPS_DIBELLA_69_() _VEILER_PELOPS_DIBELLA_68_
#define _VEILER_PELOPS_DIBELLA_70_() _VEILER_PELOPS_DIBELLA_69_
#define _VEILER_PELOPS_DIBELLA_71_() _VEILER_PELOPS_DIBELLA_70_
#define _VEILER_PELOPS_DIBELLA_72_() _VEILER_PELOPS_DIBELLA_71_
#define _VEILER_PELOPS_DIBELLA_73_() _VEILER_PELOPS_DIBELLA_72_
#define _VEILER_PELOPS_DIBELLA_74_() _VEILER_PELOPS_DIBELLA_73_
#define _VEILER_PELOPS_DIBELLA_75_() _VEILER_PELOPS_DIBELLA_74_
#define _VEILER_PELOPS_DIBELLA_76_() _VEILER_PELOPS_DIBELLA_75_
#define _VEILER_PELOPS_DIBELLA_77_() _VEILER_PELOPS_DIBELLA_76_
#define _VEILER_PELOPS_DIBELLA_78_() _VEILER_PELOPS_DIBELLA_77_
#define _VEILER_PELOPS_DIBELLA_79_() _VEILER_PELOPS_DIBELLA_78_
#define _VEILER_PELOPS_DIBELLA_80_() _VEILER_PELOPS_DIBELLA_79_
#define _VEILER_PELOPS_DIBELLA_81_() _VEILER_PELOPS_DIBELLA_80_
#define _VEILER_PELOPS_DIBELLA_82_() _VEILER_PELOPS_DIBELLA_81_
#define _VEILER_PELOPS_DIBELLA_83_() _VEILER_PELOPS_DIBELLA_82_
#define _VEILER_PELOPS_DIBELLA_84_() _VEILER_PELOPS_DIBELLA_83_
#define _VEILER_PELOPS_DIBELLA_85_() _VEILER_PELOPS_DIBELLA_84_
#define _VEILER_PELOPS_DIBELLA_86_() _VEILER_PELOPS_DIBELLA_85_
#define _VEILER_PELOPS_DIBELLA_87_() _VEILER_PELOPS_DIBELLA_86_
#define _VEILER_PELOPS_DIBELLA_88_() _VEILER_PELOPS_DIBELLA_87_
#define _VEILER_PELOPS_DIBELLA_89_() _VEILER_PELOPS_DIBELLA_88_
#define _VEILER_PELOPS_DIBELLA_90_() _VEILER_PELOPS_DIBELLA_89_
#define _VEILER_PELOPS_DIBELLA_91_() _VEILER_PELOPS_DIBELLA_90_
#define _VEILER_PELOPS_DIBELLA_92_() _VEILER_PELOPS_DIBELLA_91_
#define _VEILER_PELOPS_DIBELLA_93_() _VEILER_PELOPS_DIBELLA_92_
#define _VEILER_PELOPS_DIBELLA_94_() _VEILER_PELOPS_DIBELLA_93_
#define _VEILER_PELOPS_DIBELLA_95_() _VEILER_PELOPS_DIBELLA_94_
#define _VEILER_PELOPS_DIBELLA_96_() _VEILER_PELOPS_DIBELLA_95_
#define _VEILER_PELOPS_DIBELLA_97_() _VEILER_PELOPS_DIBELLA_96_
#define _VEILER_PELOPS_DIBELLA_98_() _VEILER_PELOPS_DIBELLA_97_
#define _VEILER_PELOPS_DIBELLA_99_() _VEILER_PELOPS_DIBELLA_98_
#define _VEILER_PELOPS_DIBELLA_100_() _VEILER_PELOPS_DIBELLA_99_

#ifdef VEILER_PELOPS_DIBELLA_LIMIT_1000
#include "dibella_1000.hpp"
#endif

#endif //_VEILER_PELOPS_DIBELLA_HPP_INCLUDED

//Copyright (C) 2012 I
//  Distributed under the Veiler Source License 1.0.
