#ifndef VEILER_PELOPS_DIBELLA_HPP_INCLUDED
#define VEILER_PELOPS_DIBELLA_HPP_INCLUDED

#define VEILER_PELOPS_DIBELLA(...) VEILER_PELOPS_DIBELLA_100_()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()(__VA_ARGS__)
#define VEILER_PELOPS_DIBELLA_0_(...) __VA_ARGS__
#define VEILER_PELOPS_DIBELLA_1_() VEILER_PELOPS_DIBELLA_0_
#define VEILER_PELOPS_DIBELLA_2_() VEILER_PELOPS_DIBELLA_1_
#define VEILER_PELOPS_DIBELLA_3_() VEILER_PELOPS_DIBELLA_2_
#define VEILER_PELOPS_DIBELLA_4_() VEILER_PELOPS_DIBELLA_3_
#define VEILER_PELOPS_DIBELLA_5_() VEILER_PELOPS_DIBELLA_4_
#define VEILER_PELOPS_DIBELLA_6_() VEILER_PELOPS_DIBELLA_5_
#define VEILER_PELOPS_DIBELLA_7_() VEILER_PELOPS_DIBELLA_6_
#define VEILER_PELOPS_DIBELLA_8_() VEILER_PELOPS_DIBELLA_7_
#define VEILER_PELOPS_DIBELLA_9_() VEILER_PELOPS_DIBELLA_8_
#define VEILER_PELOPS_DIBELLA_10_() VEILER_PELOPS_DIBELLA_9_
#define VEILER_PELOPS_DIBELLA_11_() VEILER_PELOPS_DIBELLA_10_
#define VEILER_PELOPS_DIBELLA_12_() VEILER_PELOPS_DIBELLA_11_
#define VEILER_PELOPS_DIBELLA_13_() VEILER_PELOPS_DIBELLA_12_
#define VEILER_PELOPS_DIBELLA_14_() VEILER_PELOPS_DIBELLA_13_
#define VEILER_PELOPS_DIBELLA_15_() VEILER_PELOPS_DIBELLA_14_
#define VEILER_PELOPS_DIBELLA_16_() VEILER_PELOPS_DIBELLA_15_
#define VEILER_PELOPS_DIBELLA_17_() VEILER_PELOPS_DIBELLA_16_
#define VEILER_PELOPS_DIBELLA_18_() VEILER_PELOPS_DIBELLA_17_
#define VEILER_PELOPS_DIBELLA_19_() VEILER_PELOPS_DIBELLA_18_
#define VEILER_PELOPS_DIBELLA_20_() VEILER_PELOPS_DIBELLA_19_
#define VEILER_PELOPS_DIBELLA_21_() VEILER_PELOPS_DIBELLA_20_
#define VEILER_PELOPS_DIBELLA_22_() VEILER_PELOPS_DIBELLA_21_
#define VEILER_PELOPS_DIBELLA_23_() VEILER_PELOPS_DIBELLA_22_
#define VEILER_PELOPS_DIBELLA_24_() VEILER_PELOPS_DIBELLA_23_
#define VEILER_PELOPS_DIBELLA_25_() VEILER_PELOPS_DIBELLA_24_
#define VEILER_PELOPS_DIBELLA_26_() VEILER_PELOPS_DIBELLA_25_
#define VEILER_PELOPS_DIBELLA_27_() VEILER_PELOPS_DIBELLA_26_
#define VEILER_PELOPS_DIBELLA_28_() VEILER_PELOPS_DIBELLA_27_
#define VEILER_PELOPS_DIBELLA_29_() VEILER_PELOPS_DIBELLA_28_
#define VEILER_PELOPS_DIBELLA_30_() VEILER_PELOPS_DIBELLA_29_
#define VEILER_PELOPS_DIBELLA_31_() VEILER_PELOPS_DIBELLA_30_
#define VEILER_PELOPS_DIBELLA_32_() VEILER_PELOPS_DIBELLA_31_
#define VEILER_PELOPS_DIBELLA_33_() VEILER_PELOPS_DIBELLA_32_
#define VEILER_PELOPS_DIBELLA_34_() VEILER_PELOPS_DIBELLA_33_
#define VEILER_PELOPS_DIBELLA_35_() VEILER_PELOPS_DIBELLA_34_
#define VEILER_PELOPS_DIBELLA_36_() VEILER_PELOPS_DIBELLA_35_
#define VEILER_PELOPS_DIBELLA_37_() VEILER_PELOPS_DIBELLA_36_
#define VEILER_PELOPS_DIBELLA_38_() VEILER_PELOPS_DIBELLA_37_
#define VEILER_PELOPS_DIBELLA_39_() VEILER_PELOPS_DIBELLA_38_
#define VEILER_PELOPS_DIBELLA_40_() VEILER_PELOPS_DIBELLA_39_
#define VEILER_PELOPS_DIBELLA_41_() VEILER_PELOPS_DIBELLA_40_
#define VEILER_PELOPS_DIBELLA_42_() VEILER_PELOPS_DIBELLA_41_
#define VEILER_PELOPS_DIBELLA_43_() VEILER_PELOPS_DIBELLA_42_
#define VEILER_PELOPS_DIBELLA_44_() VEILER_PELOPS_DIBELLA_43_
#define VEILER_PELOPS_DIBELLA_45_() VEILER_PELOPS_DIBELLA_44_
#define VEILER_PELOPS_DIBELLA_46_() VEILER_PELOPS_DIBELLA_45_
#define VEILER_PELOPS_DIBELLA_47_() VEILER_PELOPS_DIBELLA_46_
#define VEILER_PELOPS_DIBELLA_48_() VEILER_PELOPS_DIBELLA_47_
#define VEILER_PELOPS_DIBELLA_49_() VEILER_PELOPS_DIBELLA_48_
#define VEILER_PELOPS_DIBELLA_50_() VEILER_PELOPS_DIBELLA_49_
#define VEILER_PELOPS_DIBELLA_51_() VEILER_PELOPS_DIBELLA_50_
#define VEILER_PELOPS_DIBELLA_52_() VEILER_PELOPS_DIBELLA_51_
#define VEILER_PELOPS_DIBELLA_53_() VEILER_PELOPS_DIBELLA_52_
#define VEILER_PELOPS_DIBELLA_54_() VEILER_PELOPS_DIBELLA_53_
#define VEILER_PELOPS_DIBELLA_55_() VEILER_PELOPS_DIBELLA_54_
#define VEILER_PELOPS_DIBELLA_56_() VEILER_PELOPS_DIBELLA_55_
#define VEILER_PELOPS_DIBELLA_57_() VEILER_PELOPS_DIBELLA_56_
#define VEILER_PELOPS_DIBELLA_58_() VEILER_PELOPS_DIBELLA_57_
#define VEILER_PELOPS_DIBELLA_59_() VEILER_PELOPS_DIBELLA_58_
#define VEILER_PELOPS_DIBELLA_60_() VEILER_PELOPS_DIBELLA_59_
#define VEILER_PELOPS_DIBELLA_61_() VEILER_PELOPS_DIBELLA_60_
#define VEILER_PELOPS_DIBELLA_62_() VEILER_PELOPS_DIBELLA_61_
#define VEILER_PELOPS_DIBELLA_63_() VEILER_PELOPS_DIBELLA_62_
#define VEILER_PELOPS_DIBELLA_64_() VEILER_PELOPS_DIBELLA_63_
#define VEILER_PELOPS_DIBELLA_65_() VEILER_PELOPS_DIBELLA_64_
#define VEILER_PELOPS_DIBELLA_66_() VEILER_PELOPS_DIBELLA_65_
#define VEILER_PELOPS_DIBELLA_67_() VEILER_PELOPS_DIBELLA_66_
#define VEILER_PELOPS_DIBELLA_68_() VEILER_PELOPS_DIBELLA_67_
#define VEILER_PELOPS_DIBELLA_69_() VEILER_PELOPS_DIBELLA_68_
#define VEILER_PELOPS_DIBELLA_70_() VEILER_PELOPS_DIBELLA_69_
#define VEILER_PELOPS_DIBELLA_71_() VEILER_PELOPS_DIBELLA_70_
#define VEILER_PELOPS_DIBELLA_72_() VEILER_PELOPS_DIBELLA_71_
#define VEILER_PELOPS_DIBELLA_73_() VEILER_PELOPS_DIBELLA_72_
#define VEILER_PELOPS_DIBELLA_74_() VEILER_PELOPS_DIBELLA_73_
#define VEILER_PELOPS_DIBELLA_75_() VEILER_PELOPS_DIBELLA_74_
#define VEILER_PELOPS_DIBELLA_76_() VEILER_PELOPS_DIBELLA_75_
#define VEILER_PELOPS_DIBELLA_77_() VEILER_PELOPS_DIBELLA_76_
#define VEILER_PELOPS_DIBELLA_78_() VEILER_PELOPS_DIBELLA_77_
#define VEILER_PELOPS_DIBELLA_79_() VEILER_PELOPS_DIBELLA_78_
#define VEILER_PELOPS_DIBELLA_80_() VEILER_PELOPS_DIBELLA_79_
#define VEILER_PELOPS_DIBELLA_81_() VEILER_PELOPS_DIBELLA_80_
#define VEILER_PELOPS_DIBELLA_82_() VEILER_PELOPS_DIBELLA_81_
#define VEILER_PELOPS_DIBELLA_83_() VEILER_PELOPS_DIBELLA_82_
#define VEILER_PELOPS_DIBELLA_84_() VEILER_PELOPS_DIBELLA_83_
#define VEILER_PELOPS_DIBELLA_85_() VEILER_PELOPS_DIBELLA_84_
#define VEILER_PELOPS_DIBELLA_86_() VEILER_PELOPS_DIBELLA_85_
#define VEILER_PELOPS_DIBELLA_87_() VEILER_PELOPS_DIBELLA_86_
#define VEILER_PELOPS_DIBELLA_88_() VEILER_PELOPS_DIBELLA_87_
#define VEILER_PELOPS_DIBELLA_89_() VEILER_PELOPS_DIBELLA_88_
#define VEILER_PELOPS_DIBELLA_90_() VEILER_PELOPS_DIBELLA_89_
#define VEILER_PELOPS_DIBELLA_91_() VEILER_PELOPS_DIBELLA_90_
#define VEILER_PELOPS_DIBELLA_92_() VEILER_PELOPS_DIBELLA_91_
#define VEILER_PELOPS_DIBELLA_93_() VEILER_PELOPS_DIBELLA_92_
#define VEILER_PELOPS_DIBELLA_94_() VEILER_PELOPS_DIBELLA_93_
#define VEILER_PELOPS_DIBELLA_95_() VEILER_PELOPS_DIBELLA_94_
#define VEILER_PELOPS_DIBELLA_96_() VEILER_PELOPS_DIBELLA_95_
#define VEILER_PELOPS_DIBELLA_97_() VEILER_PELOPS_DIBELLA_96_
#define VEILER_PELOPS_DIBELLA_98_() VEILER_PELOPS_DIBELLA_97_
#define VEILER_PELOPS_DIBELLA_99_() VEILER_PELOPS_DIBELLA_98_
#define VEILER_PELOPS_DIBELLA_100_() VEILER_PELOPS_DIBELLA_99_

#ifdef VEILER_PELOPS_DIBELLA_LIMIT_1000
#include "dibella_1000.hpp"
#endif

#endif //VEILER_PELOPS_DIBELLA_HPP_INCLUDED

//Copyright (C) 2012 I
//  Distributed under the Veiler Source License 1.0.
