#ifndef _VEILER_PELOPS_ULLR_HPP_INCLUDED
#define _VEILER_PELOPS_ULLR_HPP_INCLUDED

#define VEILER_PELOPS_ULLR_COMMA _VEILER_PELOPS_ULLR_COMMA_ _VEILER_PELOPS_ULLR_LEFT_ _VEILER_PELOPS_ULLR_RIGHT_
#define VEILER_PELOPS_ULLR_CAT(a,b) _VEILER_PELOPS_ULLR_CAT_(a,b)
#define VEILER_PELOPS_ULLR_STR(a) _VEILER_PELOPS_ULLR_STR_(a)



#define _VEILER_PELOPS_ULLR_COMMA_() ,
#define _VEILER_PELOPS_ULLR_LEFT_ (
#define _VEILER_PELOPS_ULLR_RIGHT_ )
#define _VEILER_PELOPS_ULLR_CAT_(a,b) a##b
#define _VEILER_PELOPS_ULLR_STR_(a) #a

#endif //_VEILER_PELOPS_ULLR_HPP_INCLUDED

//Copyright (C) 2012 I
//  Distributed under the Veiler Source License 1.0.
